---
language: python

services:
  - docker

env:
  - TEST_SCENARIO=default

install:
  - pip install molecule docker passlib
  - ssh-keygen -b 2048 -t rsa -f /home/travis/.ssh/id_rsa -q -N ""

script:
  - "molecule test --scenario-name $TEST_SCENARIO"
